name: Activate Unity
on: [push]
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
    # Request manual activation file
    - name: Request manual activation file
      uses: webbertakken/unity-request-manual-activation-file@v1
      id: getManualLicenseFile
    # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
  requestActivation:
    name: Request activation ✔
    runs-on: ubuntu-latest
    steps:
    - name: Activate Unity
      uses: webbertakken/unity-activate@v1.1
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
