name: Build Cow-Duction

on:
  pull_request: {}
  push: {branches: [dev, master]}

env:
  UNITY_LICENSE: <?xml version="1.0" encoding="UTF-8"?><root><License id="Terms"><MachineBindings><Binding Key="1" Value="d39b8e2f4d364b2e98b06afa0c6e08c5"/><Binding Key="2" Value="d39b8e2f4d364b2e98b06afa0c6e08c5"/></MachineBindings><MachineID Value="Xxo1ZKbdPu/IATrc0mPBYANJFF0="/><SerialHash Value="06b87f9195a84b90653c1cf0ed46c8752558d9a4"/><Features><Feature Value="33"/><Feature Value="1"/><Feature Value="12"/><Feature Value="2"/><Feature Value="24"/><Feature Value="3"/><Feature Value="36"/><Feature Value="17"/><Feature Value="19"/><Feature Value="62"/></Features><DeveloperData Value="AQAAAEY0LUFINzMtWjk0Sy1LRVJNLUhDMjYtREtXTQ=="/><SerialMasked Value="F4-AH73-Z94K-KERM-HC26-XXXX"/><StartDate Value="2018-01-05T00:00:00"/><UpdateDate Value="2020-01-28T18:57:17"/><InitialActivationDate Value="2018-01-05T03:04:12"/><LicenseVersion Value="6.x"/><ClientProvidedVersion Value="2019.2.11f1"/><AlwaysOnline Value="false"/><Entitlements><Entitlement Ns="unity_editor" Tag="UnityPersonal" Type="EDITOR" ValidTo="9999-12-31T00:00:00"/></Entitlements></License><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#Terms"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>tFHrV9OwIBjEBBJpD130EEC9mtQ=</DigestValue></Reference></SignedInfo><SignatureValue>CRypqhowAxjHMzLlW2LVo2L6epwgXBWAipR7mekWsV1HQHHhOo1WZ6GLKsT9/a2EWbNFOgzB3npK+OdmUcJAbTf6WC30wodst1zzfujpo0Vz+x6+6YeY3F3U7lqfPkYCVCBZjZyFaHUjZLPnOve4KAMYUBVYh1LcfoW187wZ1PVI79nb3cC8qpIht9yw61scfNNMIWs5FOq+Izv/3PiWciKWZbvgrxPwE6O5u1l/pUY5M0Vnvd6Oh+R9mQkW9lVZWU781Ggq/nXv2v5sPZLP+czq/SNosNQR/U5FQJSIYcD3nTBTuo0VQCm6B9KEMoFaNHLaESUNTtz3dyKoYQ9siA==</SignatureValue></Signature></root>

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Cow-duction
        unityVersion:
          - 2019.1.8f1
          - 2019.2.11f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v1
      - uses: webbertakken/unity-builder@v0.8
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
