name: Build

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><root>\n    <License id=\"Terms\">\n        <MachineBindings>\n            <Binding Key=\"1\" Value=\"d39b8e2f4d364b2e98b06afa0c6e08c5\"/>\n            <Binding Key=\"2\" Value=\"d39b8e2f4d364b2e98b06afa0c6e08c5\"/>\n        </MachineBindings>\n        <MachineID Value=\"Xxo1ZKbdPu/IATrc0mPBYANJFF0=\"/>\n        <SerialHash Value=\"06b87f9195a84b90653c1cf0ed46c8752558d9a4\"/>\n        <Features>\n            <Feature Value=\"33\"/>\n            <Feature Value=\"1\"/>\n            <Feature Value=\"12\"/>\n            <Feature Value=\"2\"/>\n            <Feature Value=\"24\"/>\n            <Feature Value=\"3\"/>\n            <Feature Value=\"36\"/>\n            <Feature Value=\"17\"/>\n            <Feature Value=\"19\"/>\n            <Feature Value=\"62\"/>\n        </Features>\n        <DeveloperData Value=\"AQAAAEY0LUFINzMtWjk0Sy1LRVJNLUhDMjYtREtXTQ==\"/>\n        <SerialMasked Value=\"F4-AH73-Z94K-KERM-HC26-XXXX\"/>\n        <StartDate Value=\"2018-01-05T00:00:00\"/>\n        <UpdateDate Value=\"2020-01-28T18:57:17\"/>\n        <InitialActivationDate Value=\"2018-01-05T03:04:12\"/>\n        <LicenseVersion Value=\"6.x\"/>\n        <ClientProvidedVersion Value=\"2019.2.11f1\"/>\n        <AlwaysOnline Value=\"false\"/>\n        <Entitlements>\n            <Entitlement Ns=\"unity_editor\" Tag=\"UnityPersonal\" Type=\"EDITOR\" ValidTo=\"9999-12-31T00:00:00\"/>\n        </Entitlements>\n    </License><Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\"><SignedInfo><CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments\"/><SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/><Reference URI=\"#Terms\"><Transforms><Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/></Transforms><DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><DigestValue>tFHrV9OwIBjEBBJpD130EEC9mtQ=</DigestValue></Reference></SignedInfo><SignatureValue>CRypqhowAxjHMzLlW2LVo2L6epwgXBWAipR7mekWsV1HQHHhOo1WZ6GLKsT9/a2EWbNFOgzB3npK+OdmUcJAbTf6WC30wodst1zzfujpo0Vz+x6+6YeY3F3U7lqfPkYCVCBZjZyFaHUjZLPnOve4KAMYUBVYh1LcfoW187wZ1PVI79nb3cC8qpIht9yw61scfNNMIWs5FOq+Izv/3PiWciKWZbvgrxPwE6O5u1l/pUY5M0Vnvd6Oh+R9mQkW9lVZWU781Ggq/nXv2v5sPZLP+czq/SNosNQR/U5FQJSIYcD3nTBTuo0VQCm6B9KEMoFaNHLaESUNTtz3dyKoYQ9siA==</SignatureValue></Signature></root>"

jobs:
  requestManualActivationFile:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1

      # Request manual activation file
      - name: Request manual activation file
        uses: webbertakken/unity-request-manual-activation-file@v1
        id: getManualLicenseFile

      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Manual Activation File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  requestActivation:
    name: Request activation ✔
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1

      # Activate Unity
      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  testRunnerInEditMode:
    name: Test in editmode 📝
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Configure test runner
      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PROJECT_PATH: Cow-duction
          TEST_MODE: editmode

      # Upload artifact
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test results (edit mode)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  testRunnerInPlayMode:
    name: Test in playmode 📺
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Configure test runner
      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PROJECT_PATH: Cow-duction
          TEST_MODE: playmode

      # Upload artifact
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test results (play mode)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  testRunnerInAllModes:
    name: Test all modes ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Configure test runner
      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PROJECT_PATH: Cow-duction
          TEST_MODE: all

      # Upload artifacts
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  buildForWebGL:
    name: Build for StandaloneWindows64 🗗
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: webbertakken/unity-builder@v0.8
        with:
          projectPath: test-project
          unityVersion: 2019.1.8f1
          targetPlatform: StandaloneWindows64
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

  activateAndThenReturnLicense:
    name: returnLicense 🎈
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Activate Unity
      - name: Activate Unity
        uses: webbertakken/unity-activate@v1

      # Return License
      - name: Return license
        uses: webbertakken/unity-return-license@v0.1
